name: Push package to pypi

on:
  push:
    branches: [ main ]
    paths:
      - 'extract_office_content/**'
      - 'docs/docs.md'
      - 'setup.py'
      - '.github/workflows/gen_whl_to_pypi.yml'

jobs:
  GenerateWHL_PushPyPi:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'
          architecture: 'x64'

      - name: Unit testings
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install wheel get_pypi_latest_version
          pip install pytest
          pytest tests/test*.py

      - name: Run setup.py
        run: |
          python setup.py bdist_wheel ${{ github.event.head_commit.message }}

      # - name: Publish distribution 📦 to Test PyPI
      #   uses: pypa/gh-action-pypi-publish@v1.5.0
      #   with:
      #     password: ${{ secrets.TEST_PYPI_API_TOKEN }}
      #     repository_url: https://test.pypi.org/legacy/
      #     packages_dir:  dist/

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: dist/
